apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynamodb-replication-prod-devices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamo-replication-prod-devices
    spec:
      containers:
      - name: replicator
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        image: vungle/aws-dynamodb-cross-region-library:1.1.0
        env:
        - name: SOURCE_ENDPOINT
          value: dynamodb.us-east-1.amazonaws.com
        - name: SOURCE_TABLE
          value: prod-devices
        - name: DESTINATION_ENDPOINT
          value: dynamodb.us-west-2.amazonaws.com
        - name: DESTINATION_TABLE
          value: prod-devices
        - name: TASK_NAME
          value: prod-devices-east-to-west
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dynamodb-aws-credentials
              key: id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dynamodb-aws-credentials
              key: secret
